lidofinance/lido-oracle

app/oracle.py
Write informative one-line warning instead of traceback.
Increase SLEEP in production to 3600sec.
=> Write informative one-line warning instead of traceback #44

app/oracle.py
Switch privateKeyToAccount method to from_key https://github.com/lidofinance/lido-oracle/issues/67
Mute curl connect failure messages in tests https://github.com/lidofinance/lido-oracle/issues/68
=> Use from_key instead of privateKeyToAccount #67

Dockerfile, app/oracle.py, build.sh, helpers/get_git_info.py, tests/test_get_semver_tag.py, tests/test_log_version_on_oracle_start.py
* Allow python get_git_info.py to fail
* get_git_info.py now work on python 3.6 and git <2.22
* Unify time format in commit_datetime and build_datetime
* Remove version.json
* Update tests
https://github.com/lidofinance/lido-oracle/issues/78
=> Allow bumper to fail

tests/test_pool_metrics.py
* PoolMetrics activeValidatorBalance, MAX and MIN APR
* Test for decreasing the number of beacon validators
* If current.activeValidatorBalance = 0, assert APR is 0.
* Daily reward of 1% produces 365% APR and prints warning Staking APR too high!
* Penalties messages test
* Reasonable APR produces no warning messages
* Too low APR test (0.99% APR)
* Zero balance shows 0% APR
=> Unit tests for APR-related metric indications #89

README.md, app/metrics.py, app/oracle.py
* Rearrange and logically re-group statements in get_previous_metrics
* Remove unneccessary variables that used only once
* Change timestamp returned on the first run to latest block.
* Pass contracts, w3, beacon, genesis and other vars to get_*_metrics
via args (was taken from global before)
* Tiny cosmetic fixes (newlines, whitespaces, f-strings)
=> Move get_*_metrics to metrics module & cosmetic improvements

README.md, app/beacon.py, app/oracle.py, tests/test_configurations.py
See: https://github.com/sigp/lighthouse/pull/2149
Previous spec: https://hackmd.io/bQxMDRt1RbS1TLno8K4NPg
Current spec: https://hackmd.io/ofFJ5gOmQpu1jjHilHbdQQ
=> Fix after Lightnouse statuses change

src/modules/ejector/ejector.py, tests/modules/ejector/test_ejector.py
In the function _get_predicted_withdrawable_epoch in the file ejector.py the
maximum value of exit_epoch among validators ( max_exit_epoch_number ) can be less
than blockstamp.ref_epoch + 1 + MAX_SEED_LOOKAHEAD (according to
compute_activation_exit_epoch function). This can happen when all validators have
reached their exit_epochs and none of the validators have initiated an exit yet.
In this case max_exit_epoch_number sets to blockstamp.ref_epoch + 1 +
MAX_SEED_LOOKAHEAD , but at the same time latest_to_exit_validators_count is left
untouched with a non-zero value It leads to the reduction of the capacity of the exit queue.
=> Fix wrong exit validators count

src/metrics/prometheus/basic.py
Some functions work more than 5 minutes, so we don't see accurate prometheus histogram, so we increased buckets for requests and functions.
=> Tweak prometheus buckets

src/utils/cache.py
The only use of `cache_clear` is to make `global_lru_cache` similar to generic `lru_cache`. There was a typo, but it seems a real problem wasn't:
- a real way to clear cache in our code is calling `clear_global_cache` which clears global cache itself
- another way to be sure that we clear links, is using a weakref
=> Fix incorrect clear cache func name

src/modules/accounting/accounting.py, src/modules/ejector/ejector.py
Implement accounting `def execute_module` same as in ejector `def execute_module`
=> Fix inconsistent implementation

src/web3py/extensions/tx_utils.py, tests/web3_extentions/test_tx_utils.py
https://github.com/lidofinance/lido-oracle/issues/389
=> Fix: Transaction submission unhandled exception

Dockerfile
=> Fix: Python11 image does not have wget by default

src/modules/ejector/ejector.py
Reverts lidofinance/lido-oracle#413
=> Revert "Feat: add more logs to code and log validators request in ejector module"

src/providers/execution/contracts/staking_router.py, tests/integration/conftest.py, tests/integration/contracts/test_staking_router.py
If all cases are True, the Oracle will fall:
- Voting passed and enacted. Contract changed version.
- Current reportable reference slot points to the block before enact transaction.
- Contract is still reportable.
Correct Oracle behavior:
Oracle can correctly build report, but can't submit it, because contracnt and consensus version on ref slot differ from current onchain versions.
Current:
Oracle throws exception
=> fix: staking reward v2 backward compatibility

src/modules/ejector/ejector.py, tests/factory/no_registry.py, tests/modules/ejector/test_ejector.py
Bug:
`_get_total_active_validators` calculates all validators instead of filtering only active validators
=> Hotfix: FIx wrong active validators calculating 

Dockerfile, src/modules/csm/csm.py, tests/modules/csm/test_csm_module.py
In the case the initial epoch is set in the way the starting epoch of a reporting frame is set before enactment of a vote connecting CSM to the staking router, the existing sanity check prevents oracles from building report.
=> fix: do not fail on missing digests for stucks

fixtures/tests/modules/accounting/test_withdrawal_integration.py/test_happy_path.json, src/modules/accounting/accounting.py, src/services/exit_order/iterator.py, src/services/exit_order_v2/iterator.py, src/services/safe_border.py, src/services/withdrawal.py, tests/modules/accounting/test_withdrawal_integration.py
Some of the variables should be fetched on a latest slot instead of the referenced one
It affects relevance of the calculations
Changed fetching this variables by putting `latest` to the `eth_call`
=> Some oracle variables should be fetched on a latest slot

src/providers/consensus/client.py
Due to the new error text
```
Response from eth/v1/beacon/states/0x448ed6cac5963b47566ee7fac30f649e09ac87da3d34e2613d7f224352e735ea/validators [404] with text: \"{\"message\":\"State not found\",\"code\":404}\" returned.\n"}
```
=> fix: Prysm specific error text

src/modules/accounting/accounting.py, src/modules/csm/csm.py, src/modules/ejector/ejector.py, src/modules/submodules/consensus.py, tests/modules/submodules/consensus/test_consensus.py
get rid of self.report_contract.get_consensus_version()
I can't replace it in:
```python
def _check_contract_versions(self, blockstamp: ReferenceBlockStamp):
"""
Check if Oracle can process report on reference blockstamp.
"""
self._check_compatability(blockstamp.block_hash)
self._check_compatability('latest')
def _check_compatability(self, block_tag: BlockIdentifier):
contract_version = self.report_contract.get_contract_version(block_tag)
consensus_version = self.report_contract.get_consensus_version(block_tag)
compatibility = (contract_version, consensus_version) in self.COMPATIBLE_ONCHAIN_VERSIONS
if not compatibility:
raise IncompatibleOracleVersion(
f'Incompatible Oracle version. Block tag: {repr(block_tag)}. '
f'Expected (Contract, Consensus) versions: {', '.join(repr(v) for v in …
```
=> Replace consensus version calls

src/services/bunker_cases/abnormal_cl_rebase.py
=> Rename variable to mitigate potentially incorrect accounting for the validators effective balance

src/services/safe_border.py, tests/modules/accounting/test_safe_border_unit.py
In the bunker mode we doesn't want to filter by earliest exit epoch.
=> Removing filtration by earliest exit epoch in a prediction of earliest slashed epoch in bunker mode

src/services/exit_order_iterator.py, tests/modules/ejector/test_validator_exit_order_iterator.py
In case when all NO have forced limit flag and don't have exitable validators to eject, force_eject method gets into inf loop
=> fix: Infinity loop in force ejection

src/modules/csm/csm.py, src/modules/submodules/oracle_module.py
Currently, oracle instance can be interrupted by general Timeout in valid collecting case.
Fix can be checked by this Proof-of-Concept:
```python
import signal
import time
from timeout_decorator import timeout
@timeout(5)
def long_running_task():
print("Start...")
for i in range(10):
print(f"Iter {i}")
time.sleep(4)
reset_timeout(5)
print("Finished")
def reset_timeout(new_timeout):
signal.setitimer(signal.ITIMER_REAL, new_timeout)
print(f"Reset timeout to {new_timeout} seconds")
long_running_task()
```
=> [CSM] feat: reset main cycle timeout

.github/workflows/reproducability.yml
This code validates that we can (re)build the same tar file for a given commit twice. It won't check for high-level things (like properly pinned dependencies), but it checks if there are no stray non-deterministic files in the image (caches, timestamps, etc).
Won't work without https://github.com/lidofinance/lido-oracle/pull/663
Example of working workflow is here:  https://github.com/tdhq-org/lido-oracle/actions/runs/14155927778
Example of failed workflow (when image is not reproducible) is here: https://github.com/tdhq-org/lido-oracle/actions/runs/14158190103
=> Reproducability validation [SRE-2530]

src/modules/csm/checkpoint.py, tests/modules/csm/test_checkpoint.py
There is a case when slot on pivot_index is missing and have the same root as the last slot from the previous checkpoint. Now we are not marking it as missing and it causes double root processing. The fix is simple: get slot number of root on pivot_index and compare it with calculated pivot slot max(checkpoint_slot - SLOTS_PER_HISTORICAL_ROOT, 0) and if they are not equal it means that pivot slot is missing
=> [CSM v2] fix: missing pivot slot in block roots

.github/workflows/tests.yml, src/modules/submodules/oracle_module.py, src/providers/keys/client.py, src/web3py/extensions/lido_validators.py, tests/providers_clients/test_keys_api_client.py
Fixes #740
Describe how you tested the changes:
=> fix: fetch used module operators keys and add sanity checks
