app/oracle.py, tests/test_configurations.py, tests/utils.py
- test various configurations
- add get_log_lines
- tiny refactoring of oracle.py
=> configurations tests #65

app/oracle.py
Add handling Solidity exceptions to logic of send transaction https://github.com/lidofinance/lido-oracle/issues/64
=> Human-friendly revert reasons and hints #64

app/beacon.py, tests/responses.json, tests/test_beacon_functions.py
* Change algorithm to get balances in cycle
* Update testts
Related https://github.com/lidofinance/lido-oracle/issues/12
=> Change Prysm get balances algorithm

app/log.py, app/oracle.py, tests/test_logging_stdout_stderr.py
=> split logging to stdout and stderr #57

app/beacon.py, helpers/eth_nodes_mock.py, tests/responses.json, tests/test_beacon_functions.py
Change algorithm for calculating balances to get all validators from the beacon
Move listing of balances in a polling cycle.
issue https://github.com/lidofinance/lido-oracle/issues/43
=> Refactoring beacon balance polling #43

app/oracle.py
Issue https://github.com/lidofinance/lido-oracle/issues/79
=> Add condition when comparing pool metrics #79

build.sh
This variable will be used when executing the script from e2e in [lido-dao](https://github.com/lidofinance/lido-dao)
Issue https://github.com/lidofinance/lido-oracle/issues/76
=> Update script to use the tag variable from the enviroment #76

app/log.py, app/metrics.py, app/oracle.py, tests/test_pool_metrics.py
=> Fix APR formula

README.md
=> Improve README.md #62

app/metrics.py, app/oracle.py, tests/test_configurations.py
Cherry-picked @vshvsh 's commit 27026f49e92f84de971cb7a643dca62986877439
```
commit 27026f49e92f84de971cb7a643dca62986877439
Author: Vasiliy Shapovalov <vs@p2p.org>
Date:   Wed Dec 23 17:50:34 2020 +0300
feat: autofail deamon on strange readings
```
On top of it:
Make suspicious TX enforceable in DAEMON mode to keep e2e tests possible 
* Introduce FORCE flag, its logging and related warnings
* Allow suspicious TX sending in DAEMON mode with FORCE flag
* Adapt tests to use FORCE=1 in combination with daemon mode
closes #91
=> Suspicious tx in DEAMON mode and its enforcement

app/oracle.py
Issue https://github.com/lidofinance/lido-oracle/issues/93
=> Change deprecated methods in eth-account 

README.md, app/beacon.py, app/contracts.py, app/metrics.py, app/oracle.py, tests/test_pool_metrics.py
=> Fix timestamps of last epoch. Increase MAX_APR

Dockerfile
=> Dockerfile improve 

.dockerignore
Dockerfile doesn't work because app and assets folders are excluded incorrectly.
=> Fix dockerignore file

README.md, app/prometheus_metrics.py
Added `PROMETHEUS_PREFIX` env variable that can be used to configure prefixes for metrics
=> Add prefixes for prometheus metrics

app/beacon.py, app/metrics.py, app/oracle.py
Remove secrets from Oracle logs
=> Remove secrets from logs

.github/workflows/ci-prod.yml
=> Add wrokflow for production 

Dockerfile
fixes health check command
fixes python to force the stdout and stderr streams to be unbuffered (see logs in console) 
fixes pip to not use cache
consider: init system usage like tini
=> fix(docker): healthcheck and python error

CHANGELOG.md, README.md, app/metrics.py, app/oracle.py, poetry.lock, pyproject.toml, tests/test_configurations.py
- Split big function in two
- Add multi provider support
=> [Lido oracle] Add multi provider and split function

.github/workflows/ci-dev.yml, .github/workflows/ci-prod.yml, .github/workflows/ci-staging.yml, .github/workflows/create-tag-and-trigger-deploy.yml, .github/workflows/linters.yml, .github/workflows/prepare-release.yml, README.md
=> Add actions linter

Dockerfile
=> Fix curl version

src/main.py, src/modules/submodules/oracle_module.py, src/providers/consensus/typings.py, src/web3_extentions/lido_validators.py
- fixed enum values checks. Now it uses an iterator instead of private attributes
- Fixed confusion with block root and state root
- Fixed w3 typing by avoiding circular imports
=> Fix minor typing errors

src/modules/submodules/consensus.py, src/providers/consensus/typings.py, src/providers/keys/client.py
- `ValidatorState` and  `Validator` typings
- cast `str` to `int` in `_get_with_blockstamp`
- fix `_get_first_non_missed_slot`
=> fix: few things

src/providers/keys/typings.py, src/services/extra_data.py, src/utils/dataclass.py, tests/services/test_extra_data.py, tests/utils/test_dataclass_list.py
Fix dataclasses when dataclasses are used instead of dicts
=> Add extra data builder

src/main.py
- cache chain id and other methods
=> Caching issues

src/providers/consensus/client.py, tests/providers_clients/test_consensus_client.py
=> Remove non-cacheable args from consensus client

src/modules/accounting/accounting.py, src/modules/accounting/validator_state.py, tests/conftest.py, tests/modules/accounting/test_validator_state.py
=> Add accounting tests

src/modules/accounting/accounting.py, src/modules/submodules/consensus.py, src/providers/consensus/typings.py, src/utils/slot.py, src/web3py/extentions/tx_utils.py
=> Fix dry transactions

tests/modules/ejector/test_exit_order_iterator.py, tests/modules/ejector/test_exit_order_state_service.py
=> feat: increase exit order test coverage

README.md, src/variables.py
The same as https://github.com/lidofinance/lido-oracle/pull/327, but for oracle-v3
=> feat(oracle-v3): add a new env variable `MEMBER_PRIV_KEY_FILE`

README.md
=> feat: upgrade readme

src/services/bunker_cases/midterm_slashing_penalty.py, src/services/validator_state.py, src/web3py/extensions/lido_validators.py
=> Fix return type and var name

src/services/prediction.py, tests/modules/ejector/test_prediction.py
Optimize event match (O(n)) and improve consistency check
=> Match event optimization

.github/workflows/checks.yml, .github/workflows/tests.yml
Since all other repos have those 3 checks in checks.yml I moved it there
=> Move lido linters to checks.yml

.github/workflows/checks.yml, .github/workflows/ci-dev-goerli.yml, .github/workflows/tests.yml, tests/README.md, tests/modules/accounting/test_accounting_module.py, tests/modules/ejector/test_prediction.py
1. Fix typo in docs
2. Fix typo in test function name
=> fix: typos

Dockerfile, src/services/bunker_cases/abnormal_cl_rebase.py, src/utils/dataclass.py, tests/modules/accounting/bunker/test_bunker_abnormal_cl_rebase.py, tests/utils/test_dataclass.py
Reverts lidofinance/lido-oracle#424
=> Revert "Fix/develop hotfix"

poetry.lock, pyproject.toml, src/metrics/healthcheck_server.py, src/metrics/logging.py, tests/metrics/test_healthcheck_server.py, tests/metrics/test_logging.py
Increasing coverage for metrics module
=> Improve unit tests coverage in metrics module

fixtures/tests/modules/accounting/test_withdrawal_integration.py/test_happy_path.json, src/modules/accounting/accounting.py, src/services/exit_order/iterator.py, src/services/exit_order_v2/iterator.py, src/services/safe_border.py, src/services/withdrawal.py, tests/modules/accounting/test_withdrawal_integration.py
Reverts lidofinance/lido-oracle#576
Autogenerated
=> Revert "Some oracle variables should be fetched on a latest slot"

fixtures/tests/modules/accounting/test_withdrawal_integration.py/test_happy_path.json, src/modules/accounting/accounting.py, src/services/exit_order/iterator.py, src/services/exit_order_v2/iterator.py, src/services/safe_border.py, src/services/withdrawal.py, tests/modules/accounting/test_withdrawal_integration.py
=> Some oracle variables should be fetched on latest slot

src/providers/consensus/types.py
`indexed_validators` call iterates over all the validators in the state.
=> Cache indexed_validators

src/services/exit_order_iterator.py, tests/modules/accounting/test_validator_state.py, tests/modules/ejector/test_validator_exit_order_iterator.py
validators_requested_to_exit_but_not_eligible
=> get_filter_non_exitable_validators renaming

Dockerfile, Makefile, README.md, docs/development.md, poetry.lock, pyproject.toml
1. Security: Docker isolates the environment, reducing the risk of host compromise or data leaks from vulnerable dependencies.
2. Simplified onboarding: Developers can set up the environment quickly without manual dependency management. (+ automatic git hooks install, etc)
3. Consistency: Ensures a uniform setup across machines, minimizing "works on my machine" bugs. Also ensures all developers will use similar poetry version.
- Related task: ORC-331
- Epic: oracle-v6
Describe how you tested the changes:
=> feat(ORC-331): add docker dev image

.pre-commit-config.yaml, poetry.lock, pyproject.toml, src/modules/ejector/sweep.py, tests/modules/ejector/test_sweep.py
The problem was with data generation in `fake_beacon_state_view`. Sometimes validator has been classified as fully withdrawable. Test didn't expect that.
=> fix(ORC-384): Fix flakiness in test_get_validators_withdrawals

src/modules/ejector/ejector.py
Add missing log to future_withdrawals
- Related task: n/a
- Epic: n/a
Describe how you tested the changes:
=> chore(log): add missing log to future_withdrawals

README.md, src/modules/accounting/accounting.py
Remove stuck mentions from comments and readme
=> fix: remove stuck mentions
